# frontend/.eslintrc.yaml
# Configuration for ESLint static code analyser for front-end code.
# Documentation: <URL:https://eslint.org/docs/user-guide/configuring>.

# Base ESLint configurations from which this configuration extends.
extends: '../.eslintrc.yaml'

#Only frontend-specific stuff should go here. Inherit the rest from root.
globals:
  customisation: true
env:
  browser: true
rules:
  react/jsx-curly-spacing:
    - error
    - never
  react/jsx-equals-spacing:
    - error
    - never
  react/prop-types:
    - off
  import/no-named-as-default:
    - off
  react/jsx-filename-extension:
    - off

# TODO: These are genuine a11y issues we should fix
  jsx-a11y/anchor-has-content:
    - warn
  jsx-a11y/no-static-element-interactions:
    - warn
# TODO: This is fixed by merging selectors into reducers (if possible)
  import/prefer-default-export:
    - warn
