version: '2'
services:
  core:
    command: >
      sh -c "yarn --cwd backend
      && yarn --cwd backend e2e-seed
      && yarn start"
    environment:
      NODE_ENV: test
  test:
    image: cypress/browsers:chrome65-ff57
    volumes:
      - '.:/app'
    links:
      - core
    command: >
        bash -c "yarn --cwd app/e2e
        && yarn --cwd app/e2e test-command"
    depends_on:
      - core
