# docker-compose.yaml
# Docker Compose configuration for this code base.
# Documentation: <URL:https://docs.docker.com/compose/compose-file/>.

# Version of the configuration format in this file.
version: '2'

# Services to run for this application.
services:

  # The core Rabble Rouser service.
  core:
    build:
      context: docker/
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
    ports:
      - "3000:3000"
      - "8080:8080"
    depends_on:
      - kinesis
      - s3
    links:
      - "s3:rr-event-archive.s3"
    environment:
      NODE_ENV: development
      KINESIS_ENDPOINT: http://kinesis:4567
      S3_ENDPOINT: http://s3:4569
      LISTENER_AUTH_TOKEN: secret
      ARCHIVE_BUCKET: rr-event-archive
      STREAM_NAME: rabblerouser_stream
      TEST_STREAM_NAME: test_rabblerouser_stream
    command: sleep 2147483647 # Sleep forever, we'll shell into the container later
    stdin_open: true
    user: $UID
    tty: true

  # The Rabble Rouser event forwarder.
  event-forwarder:
    image: rabblerouser/event-forwarder
    depends_on:
      - kinesis
      - core
    environment:
      KINESIS_ENDPOINT: http://kinesis:4567
      LISTENER_ENDPOINT: http://core:3000/events
      LISTENER_AUTH_TOKEN: secret
      STREAM_NAME: rabblerouser_stream

  # The Rabble Rouser event archiver.
  event-archiver:
    image: rabblerouser/event-archiver
    depends_on:
      - kinesis
      - s3
    links:
      - "s3:rr-event-archive.s3"
    environment:
      KINESIS_ENDPOINT: http://kinesis:4567
      S3_ENDPOINT: http://s3:4569
      STREAM_NAME: rabblerouser_stream
      ARCHIVE_BUCKET: rr-event-archive

  # Amazon Kinesis data analytics service.
  kinesis:
    image: instructure/kinesalite

  # Amazon S3 storage service.
  s3:
    image: lphoward/fake-s3
