# backend/.eslintrc.yaml
# Configuration for ESLint static code analyser for front-end code.
# Documentation: <URL:https://eslint.org/docs/user-guide/configuring>.

# Base ESLint configurations from which this configuration extends.
extends: '../.eslintrc.yaml'

#Only backend-specific stuff should go here. Inherit the rest from root.

rules:
  strict: 0
  max-len: 0
  no-param-reassign: 0
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never

env:
  mocha: true
  node: true
  es6: true

globals:
  expect: true
  sinon: true
