# docker/Dockerfile.dev
# Docker instructions to assemble a container image for development.
# Documentation: <URL:https://docs.docker.com/engine/reference/builder/>.

# Base image from which to build this specific image.
FROM node:8-alpine

# Install `curl` with the Android package manager.
RUN apk add --no-cache curl

# Add a system user to run the Rabble Rouser application.
RUN adduser -D rabblerouser

# Change the working directory to the application root.
WORKDIR /app

# Set ownership of the application to the application user.
RUN chown -R rabblerouser /app

# Change the active user to the application user.
USER rabblerouser

# Declare the network ports on which the application will listen.
EXPOSE 3000


# Local variables:
# coding: utf-8
# mode: conf-space
# End:
# vim: fileencoding=utf-8 filetype=conf :
